### ISSUE TITLE
correct fomat of input and output

### ISSUE THREAD

**Issue by Becky0909** [skgabriel/mrf-modeling#1]
hi, I am interested in your work, but since I didn't find your source code so I'm still confused about the fomat of your input and output data during training and test (some examples are better~). Could you plz tell me the correct fomat to train T5 using your dataset?

**Comment by skgabriel** [comment]
Hi Becky, sorry for the late reply. The format of the input is |headline_text|relation dimension special token|news domain type special token, and the output is the generated relation. For example, "Experts discuss impact of the covid-19 pandemic on air travel" [writer_intent][covid] could be an input, and the output could be "there are concerns about how covid-19 affects air travel."
